version: '3.8'

networks:
  default:
    name: HERMES

services:
  python:
    build:
      dockerfile: ./docker/python/Dockerfile
      args:
        PYTHON_VERSION: 3
    container_name: "HERMES_python"
    working_dir: /opt/project
    volumes:
      - ./backend:/opt/project
    ports:
      - "5000:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=HERMES"
      - "traefik.http.routers.HERMES_python.rule=Host(`hermes.localhost`)"
      - "traefik.http.services.HERMES_python.loadbalancer.server.port=5000"
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
