[tool.ruff]
select = [
    "D", # pydocstyle
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "I", # isort
    "N", # pep8-naming
    "C", # flake8-comprehensions
    "B", # flake8-bugbear
    "S", # flake8-bandit
    "COM", # flake8-commas
    "PIE", # flake8-pie
    "C90", # mccabe
]
line-length = 125
target-version = "py310"

ignore = [
    "D107", # Missing docstring in `__init__`
    "D202", # No blank lines allowed after function docstring
    "D210", # No whitespaces allowed surrounding docstring text
    "D212", # Multi-line docstring summary should start at the first line
]

[tool.mypy]
strict = true
