[tool.ruff]
select = [
    "D", # pydocstyle
    "E", # pycodestyle errors
    "F", # pyflakes
    "W", # pycodestyle warnings
    "I", # isort
    "N", # pep8-naming
    "UP", # pyugrade
    "C90", # mccabe
    "TRY", # tryceratops
    "RUF", # ruff

    "PL", # pylint
    "PLC", # pylint-convention
    "PLE", # pylint-error
    "PLR", # pylint-refactor
    "PLW", # pylint-warnings

    "B", # flake8-bugbear
    "C", # flake8-comprehensions
    "Q", # flake8-quotes
    "S", # flake8-bandit
    "COM", # flake8-commas
    "PIE", # flake8-pie
    "PTH", # flake8-use-pathlib
    "SIM", # flake8-simplify
    "YTT", # flake8-bugbear
]
line-length = 125
target-version = "py310"

ignore = [
    "D105", # Missing docstring in magic methods
    "D107", # Missing docstring in __init__
    "D202", # No blank lines allowed after function docstring
    "D203", # 1 blank line required before class docstring
    "D204", # 1 blank line required after class docstring
    "D205", # 1 blank line required between summary line and description
    "D212", # Multi-line docstring summary should start at the first line
    "TRY003", # Avoid specifying long messages outside the exception class
]

[tool.ruff.flake8-quotes]
inline-quotes = "single"

[tool.ruff.pylint]
max-args = 6

[tool.mypy]
strict = true
show_error_codes = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "hermes.gui"
implicit_reexport = true
